sonar.projectKey=customer-feedback
sonar.projectName=Customer Feedback API
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.exclusions=**/__pycache__/**,.venv/**,.ruff_cache/**,.pytest_cache/**
sonar.coverage.exclusions=tests/**,run.py
sonar.sourceEncoding=UTF-8
